### ISSUE TITLE
verbosity example does not compile with Arduino IDE 2.2.1

### ISSUE THREAD

**Issue by PaulStoffregen** [mmurdoch/arduinounit#94]
![image](https://github.com/mmurdoch/arduinounit/assets/965463/c3a913e9-51b2-491d-acc0-2cfd1685735d)

```
/tmp/.arduinoIDE-unsaved2023115-1785075-93p92y.zbeov/verbosity/main.cpp:20:10: fatal error: verbosity.ino: No such file or directory
 #include "verbosity.ino"
          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: verbosity.ino: No such file or directory
```
